"""create core domain models

Revision ID: 5fba87ef8d99
Revises: 5316ace179ad
Create Date: 2026-09-06 13:23:46.337450

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import VECTOR
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fba87ef8d99'
down_revision: Union[str, Sequence[str], None] = '5316ace179ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('developer_name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=160), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('project_type', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('avoidance', 'reduction', 'removal', 'mixed', name='project_category'), nullable=False),
    sa.Column('registry', sa.String(length=160), nullable=False),
    sa.Column('registry_project_id', sa.String(length=255), nullable=True),
    sa.Column('methodology', sa.String(length=255), nullable=True),
    sa.Column('vintage_start', sa.Integer(), nullable=True),
    sa.Column('vintage_end', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('verified', 'validation_pending', 'verification_pending', 'unverified', 'unknown', name='verification_status'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'inactive', 'completed', 'unknown', name='project_status'), server_default='unknown', nullable=False),
    sa.Column('price_per_credit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('available_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('sdgs', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_quantity IS NULL OR available_quantity >= 0', name=op.f('ck_projects_quantity_non_negative')),
    sa.CheckConstraint('char_length(country_code) = 2', name=op.f('ck_projects_country_code_length')),
    sa.CheckConstraint('char_length(name) BETWEEN 2 AND 240', name=op.f('ck_projects_name_length')),
    sa.CheckConstraint('currency IS NULL OR char_length(currency) = 3', name=op.f('ck_projects_currency_length')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_projects_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_projects_longitude_range')),
    sa.CheckConstraint('price_per_credit IS NULL OR currency IS NOT NULL', name=op.f('ck_projects_priced_currency_required')),
    sa.CheckConstraint('price_per_credit IS NULL OR price_per_credit >= 0', name=op.f('ck_projects_price_non_negative')),
    sa.CheckConstraint('vintage_end IS NULL OR vintage_start IS NULL OR vintage_end >= vintage_start', name=op.f('ck_projects_vintage_period_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('external_id', name=op.f('uq_projects_external_id')),
    sa.UniqueConstraint('registry', 'registry_project_id', name='uq_projects_registry_project_id')
    )
    op.create_index('ix_projects_catalogue', 'projects', ['status', 'category', 'country_code'], unique=False)
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_country_code'), 'projects', ['country_code'], unique=False)
    op.create_index(op.f('ix_projects_data_as_of'), 'projects', ['data_as_of'], unique=False)
    op.create_index(op.f('ix_projects_developer_name'), 'projects', ['developer_name'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_index(op.f('ix_projects_registry'), 'projects', ['registry'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_verification_status'), 'projects', ['verification_status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('organization_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('buyer', 'curator', 'admin', name='user_role'), server_default='buyer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(organization_name) BETWEEN 2 AND 160', name=op.f('ck_users_organization_name_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('buyer_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('required_credits', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('risk_tolerance', sa.Enum('low', 'medium', 'high', name='risk_tolerance'), nullable=False),
    sa.Column('preferred_project_types', sa.ARRAY(sa.String(length=100)), server_default='{}', nullable=False),
    sa.Column('preferred_countries', sa.ARRAY(sa.String(length=2)), server_default='{}', nullable=False),
    sa.Column('preferred_category', sa.Enum('avoidance', 'reduction', 'removal', 'mixed', name='project_category'), nullable=True),
    sa.Column('sdg_priorities', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('minimum_quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('delivery_start', sa.Date(), nullable=True),
    sa.Column('delivery_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget > 0', name=op.f('ck_buyer_preferences_budget_positive')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_buyer_preferences_currency_length')),
    sa.CheckConstraint('char_length(name) BETWEEN 1 AND 160', name=op.f('ck_buyer_preferences_name_length')),
    sa.CheckConstraint('delivery_end IS NULL OR delivery_start IS NULL OR delivery_end >= delivery_start', name=op.f('ck_buyer_preferences_delivery_period_order')),
    sa.CheckConstraint('minimum_quality_score IS NULL OR minimum_quality_score BETWEEN 0 AND 100', name=op.f('ck_buyer_preferences_minimum_quality_score_range')),
    sa.CheckConstraint('required_credits > 0', name=op.f('ck_buyer_preferences_required_credits_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_buyer_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyer_preferences'))
    )
    op.create_index(op.f('ix_buyer_preferences_user_id'), 'buyer_preferences', ['user_id'], unique=False)
    op.create_table('carbon_credits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('vintage', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price_per_credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('data_as_of', sa.Date(), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_carbon_credits_currency_length')),
    sa.CheckConstraint('price_per_credit >= 0', name=op.f('ck_carbon_credits_price_non_negative')),
    sa.CheckConstraint('quantity_available >= 0', name=op.f('ck_carbon_credits_quantity_non_negative')),
    sa.CheckConstraint('vintage BETWEEN 1900 AND 2200', name=op.f('ck_carbon_credits_vintage_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_carbon_credits_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carbon_credits')),
    sa.UniqueConstraint('project_id', 'vintage', name='uq_carbon_credits_project_vintage')
    )
    op.create_index(op.f('ix_carbon_credits_project_id'), 'carbon_credits', ['project_id'], unique=False)
    op.create_table('project_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='document_status'), server_default='pending', nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint('page_count IS NULL OR page_count > 0', name=op.f('ck_project_documents_page_count_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_documents_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_documents'))
    )
    op.create_index(op.f('ix_project_documents_checksum_sha256'), 'project_documents', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_project_documents_project_id'), 'project_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_documents_status'), 'project_documents', ['status'], unique=False)
    op.create_table('project_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('integrity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('permanence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verification_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('co_benefits_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('value_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('delivery_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('compatibility_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('impact_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('carboniq_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('methodology_version', sa.String(length=40), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('carboniq_score IS NULL OR carboniq_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_carboniq_score_range')),
    sa.CheckConstraint('co_benefits_score IS NULL OR co_benefits_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_co_benefits_score_range')),
    sa.CheckConstraint('compatibility_score IS NULL OR compatibility_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_compatibility_score_range')),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_project_scores_confidence_range')),
    sa.CheckConstraint('delivery_score IS NULL OR delivery_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_delivery_score_range')),
    sa.CheckConstraint('impact_score IS NULL OR impact_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_impact_score_range')),
    sa.CheckConstraint('integrity_score IS NULL OR integrity_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_integrity_score_range')),
    sa.CheckConstraint('permanence_score IS NULL OR permanence_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_permanence_score_range')),
    sa.CheckConstraint('quality_score IS NULL OR quality_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_quality_score_range')),
    sa.CheckConstraint('risk_score IS NULL OR risk_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_risk_score_range')),
    sa.CheckConstraint('value_score IS NULL OR value_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_value_score_range')),
    sa.CheckConstraint('verification_score IS NULL OR verification_score BETWEEN 0 AND 100', name=op.f('ck_project_scores_verification_score_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_scores_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_scores')),
    sa.UniqueConstraint('project_id', 'methodology_version', name='uq_project_scores_project_methodology')
    )
    op.create_index(op.f('ix_project_scores_calculated_at'), 'project_scores', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_project_scores_project_id'), 'project_scores', ['project_id'], unique=False)
    op.create_table('risk_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='risk_severity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('requires_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rule_version', sa.String(length=40), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_risk_signals_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_signals'))
    )
    op.create_index(op.f('ix_risk_signals_code'), 'risk_signals', ['code'], unique=False)
    op.create_index(op.f('ix_risk_signals_detected_at'), 'risk_signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_risk_signals_project_id'), 'risk_signals', ['project_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_severity'), 'risk_signals', ['severity'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', VECTOR(dim=1536), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_document_chunks_chunk_index_non_negative')),
    sa.CheckConstraint('page_end IS NULL OR page_end > 0', name=op.f('ck_document_chunks_page_end_positive')),
    sa.CheckConstraint('page_end IS NULL OR page_start IS NULL OR page_end >= page_start', name=op.f('ck_document_chunks_page_order')),
    sa.CheckConstraint('page_start IS NULL OR page_start > 0', name=op.f('ck_document_chunks_page_start_positive')),
    sa.ForeignKeyConstraint(['document_id'], ['project_documents.id'], name=op.f('fk_document_chunks_document_id_project_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_index')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preference_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('draft', 'saved', 'ordered', name='portfolio_status'), server_default='draft', nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_credits', sa.Numeric(precision=14, scale=3), server_default='0', nullable=False),
    sa.Column('average_quality', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('portfolio_risk', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('optimizer_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_quality IS NULL OR average_quality BETWEEN 0 AND 100', name=op.f('ck_portfolios_average_quality_range')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_portfolios_currency_length')),
    sa.CheckConstraint('char_length(name) BETWEEN 2 AND 160', name=op.f('ck_portfolios_name_length')),
    sa.CheckConstraint('portfolio_risk IS NULL OR portfolio_risk BETWEEN 0 AND 100', name=op.f('ck_portfolios_portfolio_risk_range')),
    sa.CheckConstraint('total_cost >= 0', name=op.f('ck_portfolios_total_cost_non_negative')),
    sa.CheckConstraint('total_credits >= 0', name=op.f('ck_portfolios_total_credits_non_negative')),
    sa.ForeignKeyConstraint(['preference_id'], ['buyer_preferences.id'], name=op.f('fk_portfolios_preference_id_buyer_preferences'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    op.create_index(op.f('ix_portfolios_preference_id'), 'portfolios', ['preference_id'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('recommendation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preference_id', sa.Uuid(), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('project_data_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preference_id'], ['buyer_preferences.id'], name=op.f('fk_recommendation_runs_preference_id_buyer_preferences'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_runs'))
    )
    op.create_index(op.f('ix_recommendation_runs_created_at'), 'recommendation_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_runs_preference_id'), 'recommendation_runs', ['preference_id'], unique=False)
    op.create_index(op.f('ix_recommendation_runs_user_id'), 'recommendation_runs', ['user_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('credit_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allocation_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('allocation_percent BETWEEN 0 AND 100', name=op.f('ck_portfolio_items_allocation_percent_range')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_portfolio_items_quantity_positive')),
    sa.CheckConstraint('unit_price_snapshot >= 0', name=op.f('ck_portfolio_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['credit_id'], ['carbon_credits.id'], name=op.f('fk_portfolio_items_credit_id_carbon_credits'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_items_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_items')),
    sa.UniqueConstraint('portfolio_id', 'credit_id', name='uq_portfolio_items_portfolio_credit')
    )
    op.create_index(op.f('ix_portfolio_items_credit_id'), 'portfolio_items', ['credit_id'], unique=False)
    op.create_index(op.f('ix_portfolio_items_portfolio_id'), 'portfolio_items', ['portfolio_id'], unique=False)
    op.create_table('recommendation_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_run_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('trade_offs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('excluded_constraints', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.CheckConstraint('match_score BETWEEN 0 AND 100', name=op.f('ck_recommendation_items_match_score_range')),
    sa.CheckConstraint('rank >= 1', name=op.f('ck_recommendation_items_rank_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_recommendation_items_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_run_id'], ['recommendation_runs.id'], name=op.f('fk_recommendation_items_recommendation_run_id_recommendation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_items')),
    sa.UniqueConstraint('recommendation_run_id', 'project_id', name='uq_recommendation_items_run_project'),
    sa.UniqueConstraint('recommendation_run_id', 'rank', name='uq_recommendation_items_run_rank')
    )
    op.create_index(op.f('ix_recommendation_items_project_id'), 'recommendation_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_recommendation_run_id'), 'recommendation_items', ['recommendation_run_id'], unique=False)
    op.create_table('simulated_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('simulated', name='order_status'), server_default='simulated', nullable=False),
    sa.Column('total_cost_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_credits_snapshot', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('disclaimer_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_cost_snapshot >= 0', name=op.f('ck_simulated_orders_total_cost_non_negative')),
    sa.CheckConstraint('total_credits_snapshot > 0', name=op.f('ck_simulated_orders_total_credits_positive')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_simulated_orders_portfolio_id_portfolios'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_simulated_orders_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulated_orders')),
    sa.UniqueConstraint('portfolio_id', name='uq_simulated_orders_portfolio_id')
    )
    op.create_index(op.f('ix_simulated_orders_reference'), 'simulated_orders', ['reference'], unique=True)
    op.create_index(op.f('ix_simulated_orders_user_id'), 'simulated_orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulated_orders_user_id'), table_name='simulated_orders')
    op.drop_index(op.f('ix_simulated_orders_reference'), table_name='simulated_orders')
    op.drop_table('simulated_orders')
    op.drop_index(op.f('ix_recommendation_items_recommendation_run_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_project_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index(op.f('ix_portfolio_items_portfolio_id'), table_name='portfolio_items')
    op.drop_index(op.f('ix_portfolio_items_credit_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_recommendation_runs_user_id'), table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_preference_id'), table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_created_at'), table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_preference_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_risk_signals_severity'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_project_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_detected_at'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_code'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_project_scores_project_id'), table_name='project_scores')
    op.drop_index(op.f('ix_project_scores_calculated_at'), table_name='project_scores')
    op.drop_table('project_scores')
    op.drop_index(op.f('ix_project_documents_status'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_project_id'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_checksum_sha256'), table_name='project_documents')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_carbon_credits_project_id'), table_name='carbon_credits')
    op.drop_table('carbon_credits')
    op.drop_index(op.f('ix_buyer_preferences_user_id'), table_name='buyer_preferences')
    op.drop_table('buyer_preferences')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_verification_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_registry'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_developer_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_data_as_of'), table_name='projects')
    op.drop_index(op.f('ix_projects_country_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_index('ix_projects_catalogue', table_name='projects')
    op.drop_table('projects')
    postgresql.ENUM(name='order_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='portfolio_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='risk_severity').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='document_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='risk_tolerance').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='user_role').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='project_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='verification_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='project_category').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
